
[general]
	bot_name = "MAChatbridge"
	auto_rejoin = true
	seperator = "»"
	enabled = true

[debug]
	debug_messages = false

[mask_timer]
	enable_mask_timer = false

[dungeons]
	melody_title = false
	early_enter_title = true

